name: CI

on: push

jobs:
  release:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set app version
        run: echo "VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          draft: true
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitDraftDuringUpdate: true
          body: |
            * Test version ${{ env.VERSION }}

            * Test 5